# -*- coding: utf-8 -*-
"""matplotlib-Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fb-OLqYUm421YHKmckJR4qRzhzzgJ81k

Scipy:
We have the min and max temperatures in a city In India for each months of the year.
We would like to find a function to describe this and show it graphically, the dataset
given below.
Task:
1.fitting it to the periodic function
2.plot the fit
Data
Max = 39, 41, 43, 47, 49, 51, 45, 38, 37, 29, 27, 25
Min = 21, 23, 27, 28, 32, 35, 31, 28, 21, 19, 17, 18
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.optimize import curve_fit

max = [39, 41, 43, 47, 49, 51, 45, 38, 37, 29, 27, 25]
min = [21, 23, 27, 28, 32, 35, 31, 28, 21, 19, 17, 18]
month=range(0,12)
plt.scatter(month,max,color='r')
plt.scatter(month,min,color='b')
plt.show()

def fun(month,const,amp,theta):
  return (const+amp*np.cos((month+theta)*2*np.pi/12))

param_max,var=curve_fit(fun,month,max,[35,15,0])
param_min,var=curve_fit(fun,month,min,[10,10,0])

days=np.linspace(0,12,100)
plt.figure(figsize=(6,5))
plt.plot(month,max,'ro')
plt.plot(month,min,'bo')
plt.plot(days,fun(days,param_max[0],param_max[1],param_max[2]),'r-')
plt.plot(days,fun(days,param_min[0],param_min[1],param_min[2]),'b-')
plt.xlabel('Month')
plt.ylabel('Temperature($^\circ$C)')
plt.show()

"""This assignment is for visualization using matplotlib:
data to use:
url=https://raw.githubusercontent.com/Geoyi/Cleaning-Titanic-Data/master/titanic_original.csv

titanic = pd.read_csv(url)
Charts to plot:
1. Create a pie chart presenting the male/female proportion
2. Create a scatterplot with the Fare paid and the Age, differ the plot color by gender
"""

titanic=pd.read_csv('https://raw.githubusercontent.com/Geoyi/Cleaning-Titanic-Data/master/titanic_original.csv')

"""Create a pie chart presenting the male/female proportion"""

a=titanic['sex'].value_counts()
count=[a[0],a[1]]
label=[a.index[0],a.index[1]]

plt.pie(count,labels=label,autopct='%1.1f%%',colors=['blue','red'])
plt.title('male/female proportion')
plt.show()

"""Create a scatterplot with the Fare paid and the Age, differ the plot color by gender"""

titanic['sex'].isnull()

#lets drop last row as titanic[sex] is null.
df=titanic.iloc[:-1]

fig=plt.figure(figsize=(14,10))
fig,ax=plt.subplots()
clr={'male':'blue','female':'red'}
ax.scatter(df['fare'],df['age'],c=df['sex'].map(clr))
plt.show()

#result
fig,ax=plt.subplots(nrows=1,ncols=2)
ax[0].pie(count,labels=label,autopct='%1.1f%%',colors=['blue','red'])
ax[0].set_title('male/female proportion')
ax[1].scatter(df['fare'],df['age'],c=df['sex'].map(clr))
ax[1].set_xlabel('fare')
ax[1].set_ylabel('age')
plt.show()

